CREATE DATABASE dbElectrodomesticos;
USE dbElectrodomesticos;
Go

CREATE TABLE CLIENTE
(
	CODCLI char(4),
	NOMCLI varchar(60),
	APECLI varchar(80),
	EMACLI varchar(80),
	CELCLI char(9),
	DIRCLI varchar(70),
	ESTCLI char(1),
	CONSTRAINT CLIENTE_pk PRIMARY KEY  (CODCLI)
)
GO

CREATE TABLE VENDEDOR (

CODVEND char(4),
NOMVEND varchar(60),
APEVEND varchar(80),
EMAVEND varchar(80),
CELVEND char (9),
DIRVEND varchar(70),
ESTVEND char(1),
CONSTRAINT VENDEDOR_pk PRIMARY KEY  (CODVEND)

)
GO

CREATE TABLE PRODUCTO (

CODPRO char(5),
DESCPRO varchar(80),
CATPRO char(1),
PREPRO decimal(8,2),
STOCKPRO int,
ESTPRO char(1),
CONSTRAINT PRODUCTO_pk PRIMARY KEY  (CODPRO)

)
GO

CREATE TABLE PROVEEDOR (

CODPROV char(5),
RAZSOCPROV varchar(90),
RUCPROV varchar(11),
EMAPROV varchar(70),
ESTPROV char(1),
CONSTRAINT PROVEEDOR_pk PRIMARY KEY  (CODPROV)

)
GO

CREATE TABLE VENTA (

CODVEN char(5),
FECVEN datetime,
CODCLI char(4),
CODVEND char(4),
ESTVEN char(1),
CONSTRAINT VENTA_pk PRIMARY KEY  (CODVEN)

)
GO

CREATE TABLE VENTADETALLE (

IDVENDET int,
CODVEN char(5),
CODPRO char(5),
CANTPRO int ,

CONSTRAINT VENTADETALLE_pk PRIMARY KEY  (IDVENDET)
)
GO

CREATE TABLE COMPRA (

CODCOM char(5),
FECCOM datetime,
CODPROV char(5),
CODVEND char(4) ,
ESTCOM char(1),

CONSTRAINT COMPRA_pk PRIMARY KEY  (CODCOM)
)
GO

CREATE TABLE COMPRADETALLE (

IDCOMDET int,
CODCOM char(5),
CODPRO char(5),
CANTPRO int ,

CONSTRAINT COMPRADETALLE_pk PRIMARY KEY  (IDCOMDET)
)
GO

INSERT INTO CLIENTE (CODCLI,NOMCLI,APECLI,EMACLI,CELCLI,DIRCLI,ESTCLI)
VALUES
('CL01','Juana','Campos Ortíz','juana.campos@gmail.com','987485152','Av.Miraflores','A'),
('CL02','Sofía','Barrios Salcedo','sofia.barrios@outlook.com',' ','Jr.Huallaga','A'),
('CL03','Claudio','Pérez Luna','claudio.perez@outlook.com','984512147','Av.Libertadores','A'),
('CL04','Marcos','Ávila Manco','marcos.avila@yahoo.com',' ','Calle Huallaga','A'),
('CL05','Anastasio ','Salomon Inti','anastasio.salomon@gmail.com',' ','Jr.San Martín','A')
GO

INSERT INTO VENDEDOR(CODVEND,NOMVEND,APEVEND,EMAVEND,CELVEND,DIRVEND,ESTVEND)
VALUES
('VEN1','Gloria','Carrizales Paredes','gloria.carrizales@gmail.com','984574123','Calle Las Begonias','A'),
('VEN2','Gabriel','Lozada Lombardi','gabriel.lozada@gmail.com','974512368','Av.Los Girasoles','A'),
('VEN3','Gilberto','Martinez Guerra','gilberto.martinez@gmail.com',' ','Jr.Palomares','A')
GO


INSERT INTO PROVEEDOR(CODPROV,RAZSOCPROV,RUCPROV,EMAPROV,ESTPROV)
VALUES
('PRV01','LG Corporation','87542136951','informes@lg.com.pe','A'),
('PRV02','SONY','45213698741','informes@sony.com.pe','A'),
('PRV03','SAMSUNG','85321697661','informes@samsung.com.pe','A'),
('PRV04','OSTER SRL','55663214478','informes@oster.com.pe','A'),
('PRV05','ASUS','99663325478','informes@asus.com.pe','A')
GO

INSERT INTO PRODUCTO(CODPRO,DESCPRO,CATPRO,PREPRO,STOCKPRO,ESTPRO)
VALUES
('PRO01','Refigeradora LG Side By Side','1','4149',15,'A'),
('PRO02','Refigeradora SBS 602L','1','3599',10,'A'),
('PRO03','Refigeradora Top Mount 500L','1','2799',8,'A'),
('PRO04','TV SAMSUNG UHD 55"','1','1799',25,'A'),
('PRO05','Televisor 65" LG UHD 4K','1','2999',20,'A'),
('PRO06','TV CRYSTAL UHD 55','1','2299',7,'A'),
('PRO07','ASUS X415JA Core i3 10a Gen 14"','1','1099',17,'A'),
('PRO08','Lenovo IdePad 5i Intel Core i7 14"','1','3099',10,'A'),
('PRO09','Laptop HP 15-dw1085la Intel Core i3 Intel Core i7 14"','1','1600',15,'A'),
('PRO10','Galaxy A52 128G','1','1200',25,'A'),
('PRO11','Iphone 11 64GB Morado','1','2600',30,'A'),
('PRO12','Poco X3 GT 5G 256GB 8GB','1','1450',20,'A')

GO


ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (CODCLI)
    REFERENCES CLIENTE (CODCLI);
GO

ALTER TABLE VENTA ADD CONSTRAINT VENDEDOR_VENTA
    FOREIGN KEY (CODVEND)
    REFERENCES VENDEDOR (CODVEND);
GO

ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTA_VENTADETALLE
    FOREIGN KEY (CODVEN)
    REFERENCES VENTA(CODVEN);
GO

ALTER TABLE COMPRA ADD CONSTRAINT VENDEDOR_COMPRA
    FOREIGN KEY (CODVEND)
    REFERENCES VENDEDOR(CODVEND);
GO

ALTER TABLE COMPRA ADD CONSTRAINT PROVEEDOR_COMPRA
    FOREIGN KEY (CODPROV)
    REFERENCES PROVEEDOR(CODPROV);
GO


ALTER TABLE COMPRADETALLE ADD CONSTRAINT COMPRA_DETALLE
    FOREIGN KEY (CODCOM)
    REFERENCES COMPRA(CODCOM);
GO

ALTER TABLE COMPRADETALLE ADD CONSTRAINT PRODUCTO_DETALLE_COMPRA
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO(CODPRO);
GO

ALTER TABLE VENTADETALLE ADD CONSTRAINT PRODUCTO_VENTADETALLE
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO(CODPRO);
GO


CREATE TRIGGER spActualizandoStock
ON VENTADETALLE FOR INSERT,
UPDATE AS UPDATE PRODUCTO
SET  STOCKPRO = P.STOCKPRO - VD.CANTPRO
FROM PRODUCTO AS P,
	(SELECT CODPRO, CANTPRO FROM VENTADETALLE
WHERE
	CODPRO = CODPRO AND IDVENDET = (SELECT MAX(IDVENDET) FROM VENTADETALLE)) VD
WHERE P.CODPRO = VD.CODPRO;
GO


CREATE VIEW vVenta
AS
SELECT
    V.CODVEN AS IDVEN,
	C.CODCLI AS CODCLI,
    C.EMACLI AS EMACLI,
	UPPER(CONCAT(C.APECLI,' ',C.NOMCLI)) AS NOMCLI,
    V.FECVEN AS FECVEN
FROM VENTA AS V
    INNER JOIN CLIENTE AS C
    ON V.CODCLI = C.CODCLI;
GO
